# Generated by Django 6.0.1 on 2026-01-14 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeUniversitaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Année active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Année Universitaire',
                'verbose_name_plural': 'Années Universitaires',
                'db_table': 'annees_universitaires',
                'ordering': ['-date_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='date_fin_after_date_debut')],
            },
        ),
        migrations.CreateModel(
            name='Vague',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la vague')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagues', to='academic.anneeuniversitaire', verbose_name='Année universitaire')),
            ],
            options={
                'verbose_name': 'Vague',
                'verbose_name_plural': 'Vagues',
                'db_table': 'vagues',
                'ordering': ['annee_universitaire', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'annee_universitaire'), name='unique_vague_per_year')],
            },
        ),
    ]
